require './models/borrower'

Borrower.create({
				 	name: "Nick Ursetta",
				 	address: "2568 Danbury Lane, Highlands Ranch, CO 80126",
				 	phone_number: "303-907-2289",
				 	email: "n_ursetta@yahoo.com",
				 income: " ",
				 	base_monthly_income: 10000,
				 	bonus_monthly_income: 0,
				 	commision_monthly_income: 0,
				 	net_rental_income: 0,
				 expenses: " ",
				 	rent: 1000,
				 	mortgage_payment_monthly: 0,
				 	credit_card_payments: 500,
				 	auto_loan_payments: 384,
				 	installment_loan_payments: 0,
				 new_mortgage_information: " ",
				 	home_price: 250000,
				 	loan_amount: 200000,
				 	interest_rate: 4,
				 	monthly_pi: 898,
				 	monthly_ti: 150,
				 	monthly_hoa: 250,
				 	total_monthly_payment: 1298,
				 	credit_score: 740,
	  				type_of_employment: "W2",
	  				length_of_employment: 2
				})

Borrower.create({
				 	name: "Count Dracula",
				 	address: "1001 Fang Court, Denver, CO 80202",
				 	phone_number: "303-123-4568",
				 	email: "garlichater123@yahoo.com",
				 income: " ",
				 	base_monthly_income: 4000,
				 	bonus_monthly_income: 0,
				 	commision_monthly_income: 0,
				 	net_rental_income: 0,
				 expenses: " ",
				 	rent: 1000,
				 	mortgage_payment_monthly: 0,
				 	credit_card_payments: 1000,
				 	auto_loan_payments: 200,
				 	installment_loan_payments: 0,
				 new_mortgage_information: " ",
				 	home_price: 250000,
				 	loan_amount: 200000,
				 	interest_rate: 4,
				 	monthly_pi: 898,
				 	monthly_ti: 150,
				 	monthly_hoa: 250,
				 	total_monthly_payment: 1298,
				 	credit_score: 540,
	  				type_of_employment: "Self Employed",
	  				length_of_employment: 2
				})

Borrower.create({
				 	name: "Frankenstein",
				 	address: "9876 Monster Mash Lane, Denver, CO 80202",
				 	phone_number: "303-987-6543",
				 	email: "IWillEatYou@gmail.com",
				 income: " ",
				 	base_monthly_income: 10000,
				 	bonus_monthly_income: 0,
				 	commision_monthly_income: 0,
				 	net_rental_income: 0,
				 expenses: " ",
				 	rent: 1000,
				 	mortgage_payment_monthly: 0,
				 	credit_card_payments: 500,
				 	auto_loan_payments: 384,
				 	installment_loan_payments: 0,
				 new_mortgage_information: " ",
				 	home_price: 500000,
				 	loan_amount: 400000,
				 	interest_rate: 5,
				 	monthly_pi: 2148,
				 	monthly_ti: 150,
				 	monthly_hoa: 250,
				 	total_monthly_payment: 2548,
				 	credit_score: 850,
	  				type_of_employment: "W2",
	  				length_of_employment: 2
				})